services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tpearl
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

